version: '3.9'
services:
  dev-db:
    image: postgres:16.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - localNetwork
networks:
  localNetwork:

#   networks:
#       - freecodecamp
# networks:
#   freecodecamp: